import { promises as fs } from 'node:fs';
import path from 'node:path';
import { NEVER_WALK, walkFiles } from './walk.mjs';

// Copy-time policy, distinct from what a walk skips in general: a lockfile in
// the template pins the template author's install, not the new project's, so
// it is regenerated by `pnpm install` rather than copied. Kept separate from
// NEVER_WALK so revisiting that decision cannot silently change what
// placeholder rewriting touches.
const TEMPLATE_EXCLUDES = new Set([
  ...NEVER_WALK,
  'pnpm-lock.yaml',
  'package-lock.json',
  'yarn.lock',
]);

export async function copyTemplate(srcDir, destDir, { exclude = TEMPLATE_EXCLUDES } = {}) {
  if (await pathHasEntries(destDir)) {
    throw new Error(`Destination already exists and is not empty: ${destDir}`);
  }
  await fs.mkdir(destDir, { recursive: true });
  await walkFiles(
    srcDir,
    async (srcPath) => {
      const destPath = path.join(destDir, path.relative(srcDir, srcPath));
      await fs.mkdir(path.dirname(destPath), { recursive: true });
      await fs.copyFile(srcPath, destPath);
    },
    { exclude }
  );
}

async function pathHasEntries(dir) {
  try {
    const entries = await fs.readdir(dir);
    return entries.length > 0;
  } catch (error) {
    if (error.code === 'ENOENT') return false;
    throw error;
  }
}
